version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=snapes
      - FLASK_ENV=development
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"